version: '3'

services:
  some-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=devops
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3307:3306

  app:
    image: devopscasestudy:latest
    ports:
       - 8888:8888
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://some-mysql:3306/devops?autoReconnect=true&useSSL=false
    depends_on:
       - some-mysql